[0.000000] (-) TimerEvent: {}
[0.000799] (-) JobUnselected: {'identifier': 'custom_messages'}
[0.001028] (-) JobUnselected: {'identifier': 'rviz_basic'}
[0.001450] (easy_robot_control) JobQueued: {'identifier': 'easy_robot_control', 'dependencies': OrderedDict()}
[0.001834] (easy_robot_control) JobStarted: {'identifier': 'easy_robot_control'}
[0.099310] (-) TimerEvent: {}
[0.200351] (-) TimerEvent: {}
[0.301539] (-) TimerEvent: {}
[0.403607] (-) TimerEvent: {}
[0.504989] (-) TimerEvent: {}
[0.605824] (-) TimerEvent: {}
[0.706473] (-) TimerEvent: {}
[0.807166] (-) TimerEvent: {}
[0.907818] (-) TimerEvent: {}
[1.008600] (-) TimerEvent: {}
[1.110299] (-) TimerEvent: {}
[1.212017] (-) TimerEvent: {}
[1.312697] (-) TimerEvent: {}
[1.413511] (-) TimerEvent: {}
[1.514105] (-) TimerEvent: {}
[1.614734] (-) TimerEvent: {}
[1.624438] (easy_robot_control) StderrLine: {'line': b'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_parallel_executor/executor/parallel.py", line 75, in execute\n    loop.run_until_complete(future)\n  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete\n    self.run_forever()\n  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever\n    self._run_once()\n  File "/usr/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once\n    event_list = self._selector.select(timeout)\n  File "/usr/lib/python3.8/selectors.py", line 468, in select\n    fd_event_list = self._selector.poll(timeout, max_ev)\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__\n    rc = await self.task(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__\n    return await task_method(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 102, in build\n    return await extension.build(additional_hooks=additional_hooks)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 85, in build\n    available_commands = await self._get_available_commands(\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 175, in _get_available_commands\n    output = await check_output(\n  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 129, in check_output\n    assert not rc, f\'Expected {args} to pass: {stderr_data}\'\nAssertionError: Expected [\'/usr/bin/python3\', \'setup.py\', \'--help-commands\'] to pass: Traceback (most recent call last):\n  File "setup.py", line 1, in <module>\n    from setuptools import setup\n  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 17, in <module>\n    import setuptools.version\n  File "/usr/lib/python3/dist-packages/setuptools/version.py", line 1, in <module>\n    import pkg_resources\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>\n    def _initialize_master_working_set():\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside\n    f(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3289, in _initialize_master_working_set\n    list(map(working_set.add_entry, sys.path))\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 624, in add_entry\n    for dist in find_distributions(entry, True):\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2066, in find_on_path\n    for dist in factory(fullpath):\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2135, in distributions_from_metadata\n    yield Distribution.from_location(\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2592, in from_location\n    return cls(\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2996, in _reload_version\n    md_version = self._get_version()\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2774, in _get_version\n    version = _version_from_file(lines)\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2558, in _version_from_file\n    line = next(iter(version_lines), \'\')\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2769, in _get_metadata\n    for line in self.get_metadata_lines(name):\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1433, in get_metadata_lines\n    return yield_lines(self.get_metadata(name))\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1421, in get_metadata\n    value = self._get(path)\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1617, in _get\n    with open(path, \'rb\') as stream:\nKeyboardInterrupt\n\n'}
[1.625754] (easy_robot_control) JobEnded: {'identifier': 'easy_robot_control', 'rc': 'SIGINT'}
[1.635906] (-) EventReactorShutdown: {}
